name: Example
version: 0.0.9
slug: example
description: Example add-on by Community Home Assistant Apps
url: https://github.com/ioncb-hassio-addons/app-example
init: false
arch:
  - aarch64
  - amd64
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
image: ghcr.io/ioncb-hassio-addons/example
